export const FETCH_USER = "FETCH_USER";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const FETCH_USER_FAILED = "FETCH_USER_FAILED";
export const USER_SIGN_OUT = "USER_SIGN_OUT";
export const USER_NOT_REGISTERED = "USER_NOT_REGISTERED";
export const USER_SIGN_IN = "USER_SIGN_IN";
export const USER_SIGN_IN_FAILED = "SIGN_IN_FAILED";
export const CLEAR_LOGIN_ERROR = "CLEAR_LOGIN_ERROR";
export const UPDATE_USER_PROFILE = "UPDATE_USER_PROFILE";
export const UPDATE_USER_PROFILE_FAILED = "UPDATE_USER_PROFILE_FAILED";
export const NEW_USER_PROFILE_ROUTE = "NEW_USER_PROFILE_ROUTE";

//Login Types
export const SHOW_LOADER_LOGIN = "SHOW_LOADER_LOGIN";
export const LOGIN_EMAIL = "LOGIN_EMAIL";
export const LOGIN_PASSWORD = "LOGIN_PASSWORD";
export const EMAIL_SIGN_IN = "EMAIL_SIGN_IN";
export const EMAIL_SIGN_IN_SUCCESS = "EMAIL_SIGN_IN_SUCCESS";
export const EMAIL_SIGN_IN_FAILED = "EMAIL_SIGN_IN_FAILED";
export const EMAIL_REGISTER = "EMAIL_REGISTER";
export const EMAIL_REGISTER_SUCCESS = "EMAIL_REGISTER_SUCCESS";
export const EMAIL_REGISTER_FAILED = "EMAIL_REGISTER_FAILED";
export const SEND_RESET_EMAIL = "SEND_RESET_EMAIL";
export const SEND_RESET_EMAIL_SUCCESS = "SEND_RESET_EMAIL_SUCCESS";
export const SEND_RESET_EMAIL_FAILED = "SEND_RESET_EMAIL_FAILED";
export const USER_DELETED = "USER_DELETED";

//Home Types
export const SHOW_LOADER_HOME = "SHOW_LOADER_HOME";
export const FETCH_TOTAL_USERS = "FETCH_TOTAL_USERS";
export const FETCH_TOTAL_PRODUCTS = "FETCH_TOTAL_PRODUCTS";
export const FETCH_TOTAL_RECEIVED_QUOTES = "FETCH_TOTAL_RECEIVED_QUOTES";
export const FETCH_TOTAL_SEND_QUOTES = "FETCH_TOTAL_SEND_QUOTES";
export const FETCH_TOTAL_COMPLETE_ORDER = "FETCH_TOTAL_COMPLETE_ORDER";
export const FETCH_TOTAL_REPORTS = "FETCH_TOTAL_REPORTS";
export const FETCH_GROWTH_METRICS = "FETCH_GROWTH_METRICS";

//User Types
export const FETCH_ALL_USERS = "FETCH_ALL_USERS";
export const FETCH_ALL_USERS_SUCCESS = "FETCH_ALL_USERS_SUCCESS";
export const FETCH_ALL_USERS_FAILED = "FETCH_ALL_USERS_FAILED";
export const ADD_USERS_SUCCESS = "ADD_USERS_SUCCESS";
export const ADD_USERS_DATA = "ADD_USERS_DATA";
export const ADD_USERS_FAILED = "ADD_USERS_FAILED";
export const USER_RESET = "USER_RESET";
export const USER_FIRSTNAME = "USER_FIRSTNAME";
export const USER_LASTNAME = "USER_LASTNAME";
export const USER_EMAIL = "USER_EMAIL";
export const USER_MOBILENUMBER = "USER_MOBILENUMBER";
export const USER_COMPANYNAME = "USER_COMPANYNAME";
export const USER_GSTNUMBER = "USER_GSTNUMBER";
export const USER_SEARCH_DATA = "USER_SEARCH_DATA";
export const CLEAR_USER_ERROR = "CLEAR_USER_ERROR";

//Product Types
export const SHOW_LOADER_PRODUCT = "SHOW_LOADER_PRODUCT";
export const CLEAR_PRODUCT_ERROR = "CLEAR_PRODUCT_ERROR";
export const FETCH_ALL_PRODUCTS = "FETCH_ALL_PRODUCTS";
export const FETCH_ALL_PRODUCTS_SUCCESS = "FETCH_ALL_PRODUCTS_SUCCESS";
export const FETCH_ALL_PRODUCTS_FAILED = "FETCH_ALL_PRODUCTS_FAILED";
export const ADD_PRODUCTS_SUCCESS = "ADD_PRODUCTS_SUCCESS";
export const ADD_PRODUCTS_FAILED = "ADD_PRODUCTS_FAILED";
export const EDIT_PRODUCTS_SUCCESS = "EDIT_PRODUCTS_SUCCESS";
export const EDIT_PRODUCTS_FAILED = "EDIT_PRODUCTS_FAILED";
export const PRODUCT_RESET = "PRODUCT_RESET";
export const PRODUCT_TITLE = "PRODUCT_TITLE";
export const PRODUCT_DESC = "PRODUCT_DESC";
export const PRODUCT_QUANTITY_TYPE = "PRODUCT_QUANTITY_TYPE";
export const PRODUCT_IMAGE = "PRODUCT_IMAGE";
export const PRODUCT_IMAGE_BLOB = "PRODUCT_IMAGE_BLOB";
export const PRODUCT_SEARCH_DATA = "PRODUCT_SEARCH_DATA";
export const PRODUCT_SEARCH_SEARCH_DATA = "PRODUCT_SEARCH_SEARCH_DATA";

//Cart Types
export const SHOW_LOADER_CART = "SHOW_LOADER_CART";
export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS";
export const ADD_TO_CART_FAIL = "ADD_TO_CART_FAIL";
export const CLEAR_CART_ERROR = "CLEAR_CART_ERROR";
export const CLEAR_CART = "CLEAR_CART";
export const FETCH_CART_COUNT = "FETCH_CART_COUNT";
export const FETCH_CART_PRODUCT = "FETCH_CART_PRODUCT";
export const FETCH_CART_PRODUCT_SUCCESS = "FETCH_CART_PRODUCT_SUCCESS";
export const FETCH_CART_PRODUCT_FAILED = "FETCH_CART_PRODUCT_FAILED";
export const SUBMIT_FOR_QUOTE_SUCCESS = "SUBMIT_FOR_QUOTE_SUCCESS";
export const SUBMIT_FOR_QUOTE_FAILED = "SUBMIT_FOR_QUOTE_FAILED";

//Search Location or GPS
export const UPDATE_GPS_LOCATION = "UPDATE_GPS_LOCATION";
export const SHOW_LOADER_SEARCH_LOCATION = "SHOW_LOADER_SEARCH_LOCATION";
export const SAVE_ADDRESS_SUCCESS = "SAVE_ADDRESS_SUCCESS";
export const SAVE_ADDRESS_FAIL = "SAVE_ADDRESS_FAIL";
export const CLEAR_SAVE_ADDRESS_ERROR = "CLEAR_SAVE_ADDRESS_ERROR";
export const FETCH_SAVE_ADDRESS_SUCCESS = "FETCH_SAVE_ADDRESS_SUCCESS";
export const FETCH_SAVE_ADDRESS_FAILED = "FETCH_SAVE_ADDRESS_FAILED";
export const DELETE_SAVED_ADDRESS_SUCCESS = "DELETE_SAVED_ADDRESS_SUCCESS";

//Order Types
export const SHOW_LOADER_ORDER = "SHOW_LOADER_ORDER";
export const CLEAR_ORDER_ERROR = "CLEAR_ORDER_ERROR";
export const SHOW_ORDER_ERROR = "SHOW_ORDER_ERROR";
export const QUOTE_CHANGE_SUCCESS = "QUOTE_CHANGE_SUCCESS";
export const FETCH_QUOTE_REQUEST_SUCCESS = "FETCH_QUOTE_REQUEST_SUCCESS";
export const FETCH_QUOTE_REQUEST_FAILED = "FETCH_QUOTE_REQUEST_FAILED";
export const FETCH_QUOTE_SEND_SUCCESS = "FETCH_QUOTE_SEND_SUCCESS";
export const FETCH_QUOTE_SEND_FAILED = "FETCH_QUOTE_SEND_FAILED";
export const FETCH_QUOTE_RECEIVED_SUCCESS = "FETCH_QUOTE_RECEIVED_SUCCESS";
export const FETCH_QUOTE_RECEIVED_FAILED = "FETCH_QUOTE_RECEIVED_FAILED";
export const FETCH_ORDER_SUCCESS = "FETCH_ORDER_SUCCESS";
export const FETCH_ORDER_FAILED = "FETCH_ORDER_FAILED";
export const FETCH_ORDER_CONFIRMED_PROCESSING_SUCCESS = "FETCH_ORDER_CONFIRMED_PROCESSING_SUCCESS";
export const FETCH_ORDER_CONFIRMED_PROCESSING_FAILED = "FETCH_ORDER_CONFIRMED_PROCESSING_FAILED";
export const FETCH_ORDER_CONFIRM_SUCCESS = "FETCH_ORDER_CONFIRM_SUCCESS";
export const FETCH_ORDER_CONFIRM_FAILED = "FETCH_ORDER_CONFIRM_FAILED";
export const ORDER_FROMDATE = "ORDER_FROMDATE";
export const ORDER_TODATE = "ORDER_TODATE";

//Chat Types
export const SHOW_LOADER_CHAT = "SHOW_LOADER_CHAT";
export const OPEN_CHAT_SUCCESS = "OPEN_CHAT_SUCCESS";
export const CLEAR_CHAT_ERROR = "CLEAR_CHAT_ERROR";
export const ADD_CHATBOARD_DATA = "ADD_CHATBOARD_DATA";
export const CLEAR_CHATBOARD_DATA = "CLEAR_CHATBOARD_DATA";

//Notification Broadcast Types
export const SHOW_LOADER_NB = "SHOW_LOADER_NB";
export const CLEAR_NB_ERROR = "CLEAR_NB_ERROR";
export const SHOW_NB_ERROR = "SHOW_NB_ERROR";
export const FETCH_NB_SUCCESS = "FETCH_NB_SUCCESS";
export const FETCH_NB_FAILED = "FETCH_NB_FAILED";
export const UPDATE_NB_USER = "UPDATE_NB_USER";
export const NB_NOTIFICATION_TITLE = "NB_NOTIFICATION_TITLE";
export const NB_NOTIFICATION_BODY = "NB_NOTIFICATION_BODY";
export const NB_SEND_SUCCESS = "NB_SEND_SUCCESS";

//Reports Types
export const SHOW_LOADER_REPORTS = "SHOW_LOADER_REPORTS";
export const CLEAR_REPORTS_ERROR = "CLEAR_REPORTS_ERROR";
export const SHOW_REPORTS_ERROR = "SHOW_REPORTS_ERROR";
export const REPORTS_PRODUCT_ID = "REPORTS_PRODUCT_ID";
export const FETCH_REPORT_SUCCESS = "FETCH_REPORT_SUCCESS";
export const FETCH_REPORT_FAILED = "FETCH_REPORT_FAILED";